version: '3.4'
services:
  pgsql:
    image: postgres
    container_name: pgsql
    restart: always
    volumes:
      - "./data/postgresql:/var/lib/postgresql/data"
    environment:
      TZ: "Asia/Shanghai"
      POSTGRES_USER: postgres
      POSTGRES_DB: IoTSharp
      POSTGRES_PASSWORD: future 
    ports: 
     - "5432:5432"
    networks:
      - iotsharp-network


  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    volumes:
       - "./data/servers.json:/pgadmin4/servers.json"
    depends_on:
      - pgsql 
    links:
      - pgsql
    ports:
      - 8090:80
    environment:
      TZ: "Asia/Shanghai"
      PGADMIN_DEFAULT_EMAIL: "root@iotsharp.io"
      PGADMIN_DEFAULT_PASSWORD: "1-q2-w3-e4-r5-t"
    networks:
      - iotsharp-network

  iotsharp:
    image: maikebing/iotsharp:latest
    restart: always
    container_name: iotsharp
    hostname: iotsharp
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      TZ: Asia/Shanghai
    depends_on:
      - pgsql
      - mongodb1
      - mongodb2
      - mongodb3
      - rabbitmq
      - influx
    links:
      - pgsql
      - mongodb1
      - mongodb2
      - mongodb3
      - rabbitmq
      - influx
    volumes:
      - "./appsettings.Production.json:/app/appsettings.Production.json"
    ports:
      - 2927:80
      - 1883:1883
      - 8883:8883 
      - 5683:5683
      - 5684:5684
      - 502:502
    networks:
      - iotsharp-network
       


  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    restart: always
    hostname: mq
    ports:
      - 15672:15672
      - 5672:5672
    volumes:
      - ./data/rabbitmq:/var/lib/rabbitmq
    environment:
      - TZ=Asia/Shanghai
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=kissme
    networks:
      - iotsharp-network


  mongodb1:
    image: mongo:latest
    restart: always
    container_name: mongodb1
    volumes:
      - ./data/mongodb1/db:/data/db
      - ./data/mongodb1/log:/var/log/mongodb
      - ./mongodb-init.sh:/scripts/mongodb-init.sh
    ports:
      - 27017:27017
    links:
      - mongodb2
      - mongodb3
    environment:
      TZ: "Asia/Shanghai"
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: kissme
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - iotsharp-network
      
  mongodb2:
    container_name: mongodb2
    image: mongo:latest
    volumes:
      - ./data/mongodb2/db:/data/db
      - ./data/mongodb2/log:/var/log/mongodb
    ports:
      - 27018:27017
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: kissme
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - iotsharp-network
    
  mongodb3:
    container_name: mongodb3
    image: mongo:latest
    volumes:
      - ./data/mongodb3/db:/data/db
      - ./data/mongodb3/log:/var/log/mongodb
    ports:
      - 27019:27017
    restart: always
    environment:
      TZ: "Asia/Shanghai"
      #MONGO_INITDB_ROOT_USERNAME: root
      #MONGO_INITDB_ROOT_PASSWORD: kissme
    entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "dbrs" ]
    networks:
      - iotsharp-network

  influx:
        image: "quay.io/influxdb/influxdb:v2.0.4"
        restart: always
        container_name: influx
        ports:
         - "8086:8086"
        environment:
          TZ: "Asia/Shanghai"
        volumes:
         - ./data/influxdb-data:/var/lib/influxdb2
        command: influxd run --bolt-path /var/lib/influxdb2/influxd.bolt --engine-path /var/lib/influxdb2/engine --store bolt
        networks:
          - iotsharp-network

  influxdb_cli:
    links:
        - influx
    image: quay.io/influxdb/influxdb:v2.0.4
    entrypoint: influx setup --bucket iotsharp-bucket -t iotsharp-token -o iotsharp --username=root --password=1-q2-w3-e4-r5-t --host=http://influx:8086 -f
    restart: on-failure:20
    depends_on:
         - influx


 

networks: 
  iotsharp-network:
      driver:  bridge

