name: .NET Core build

on:
  push:
    branches: [ master ]
    paths: [IoTSharp.*/**,IoTSharp/**]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: InferSharp
      uses: microsoft/infersharpaction@v0.2
    - name: Setup .NET Core SDK
      uses: actions/setup-dotnet@v1.7.2
      with: 
        dotnet-version: 7.0.x 
    - name: Build
      run: dotnet build  ./IoTSharp.sln  --configuration Release 

      
      
